<script setup>
import AppPageHeader from '@/components/AppPageHeader.vue';
import EmptyState from '@/components/EmptyState.vue';
import MoneyText from '@/components/MoneyText.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { router } from '@inertiajs/vue3';
import Column from 'primevue/column';
import DataTable from 'primevue/datatable';
import DatePicker from 'primevue/datepicker';
import SelectButton from 'primevue/selectbutton';
import { ref, watch } from 'vue';

const props = defineProps({
    aging: { type: Object, required: true },
    kind: { type: String, required: true },
    header: { type: Object, required: true },
    buckets: { type: Array, required: true },
});

const kind = ref(props.kind);
const asOf = ref(new Date(props.aging.as_of));

const KINDS = [
    { label: 'Receivables', value: 'receivables' },
    { label: 'Payables', value: 'payables' },
];

const LABELS = {
    current: 'Current',
    '1_30': '1–30 days',
    '31_60': '31–60 days',
    '61_90': '61–90 days',
    over_90: 'Over 90 days',
};

const asDate = (value) =>
    `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`;

const reload = () => {
    router.get(
        route('reports.aging'),
        { kind: kind.value, as_of: asDate(asOf.value) },
        { preserveState: true, replace: true }
    );
};

watch([kind, asOf], reload);
</script>

<template>
    <AuthenticatedLayout :title="header.title">
        <template #header>
            <AppPageHeader
                :title="header.title"
                subtitle="Read from the subledger — a cash-basis registrant has no A/R control account, and still needs to know who owes what"
            />
        </template>

        <div class="card">
            <div class="mb-4 flex flex-wrap items-end gap-4">
                <SelectButton v-model="kind" :options="KINDS" optionLabel="label" optionValue="value" :allowEmpty="false" />
                <div>
                    <label for="as_of" class="mb-2 block text-sm font-medium">As of</label>
                    <DatePicker id="as_of" v-model="asOf" dateFormat="dd M yy" showIcon />
                </div>
            </div>

            <DataTable :value="aging.partners" dataKey="partner_id" class="p-datatable-sm" responsiveLayout="scroll">
                <template #empty>
                    <EmptyState
                        icon="pi pi-check-circle"
                        title="Nothing outstanding"
                        hint="Every document is settled as of this date."
                    />
                </template>

                <Column field="registered_name" header="Partner" class="min-w-64" />

                <Column v-for="bucket in buckets" :key="bucket" :header="LABELS[bucket]" class="min-w-32 text-right">
                    <template #body="{ data }">
                        <MoneyText v-if="data[bucket]" :centavos="data[bucket]" :symbol="false" />
                        <span v-else class="text-muted-color">—</span>
                    </template>
                </Column>

                <Column header="Total" class="min-w-32 text-right">
                    <template #body="{ data }">
                        <span class="font-semibold"><MoneyText :centavos="data.total" :symbol="false" /></span>
                    </template>
                </Column>

                <template #footer>
                    <div class="flex flex-wrap justify-end gap-6 pt-2 text-sm">
                        <div v-for="bucket in buckets" :key="bucket" class="text-right">
                            <div class="text-muted-color">{{ LABELS[bucket] }}</div>
                            <MoneyText :centavos="aging.totals[bucket]" />
                        </div>
                        <div class="text-right">
                            <div class="font-semibold">Total</div>
                            <span class="font-semibold"><MoneyText :centavos="aging.totals.total" /></span>
                        </div>
                    </div>
                </template>
            </DataTable>
        </div>

        <!--
            The header/footer block BIR requires on every generated report
            (RMC 5-2021 Annex B item 4).
        -->
        <div class="card text-xs text-muted-color">
            <div>{{ header.registered_name }} — {{ header.tin }}</div>
            <div>{{ header.registered_address }}</div>
            <div>
                {{ header.software }}
                <template v-if="header.accn"> · ACCN {{ header.accn }}</template>
                · generated by {{ header.generated_by }} on {{ header.generated_at }}
            </div>
        </div>
    </AuthenticatedLayout>
</template>
