<script setup>
import AppPageHeader from '@/components/AppPageHeader.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import Button from 'primevue/button';
import { computed } from 'vue';

/**
 * The frame every financial report shares (spec 11 §3): title, filter bar,
 * export buttons, and the header/footer block RMC 5-2021 Annex B item 4
 * requires on EVERY generated output. Putting the block here means a report
 * page cannot forget it.
 */
const props = defineProps({
    title: { type: String, required: true },
    subtitle: { type: String, default: null },
    header: { type: Object, required: true },
    /** Current query params, re-sent with the export request. */
    params: { type: Object, default: () => ({}) },
    exportRoute: { type: String, required: true },
});

const FORMATS = [
    { format: 'pdf', label: 'PDF', icon: 'pi pi-file-pdf' },
    { format: 'xlsx', label: 'Excel', icon: 'pi pi-file-excel' },
    { format: 'csv', label: 'CSV', icon: 'pi pi-file' },
];

const exportUrl = computed(
    () => (format) => route(props.exportRoute, { ...props.params, format })
);
</script>

<template>
    <AuthenticatedLayout :title="title">
        <template #header>
            <AppPageHeader :title="title" :subtitle="subtitle">
                <template #actions>
                    <a v-for="f in FORMATS" :key="f.format" :href="exportUrl(f.format)">
                        <Button :label="f.label" :icon="f.icon" outlined size="small" />
                    </a>
                </template>
            </AppPageHeader>
        </template>

        <div v-if="$slots.filters" class="card flex flex-wrap items-end gap-4">
            <slot name="filters" />
        </div>

        <slot />

        <div class="card text-xs text-muted-color">
            <div>{{ header.registered_name }} — {{ header.tin }}</div>
            <div>{{ header.registered_address }}</div>
            <div>
                {{ header.software }}
                <template v-if="header.accn"> · ACCN {{ header.accn }}</template>
                · generated by {{ header.generated_by }} on {{ header.generated_at }}
            </div>
        </div>
    </AuthenticatedLayout>
</template>
