<?php

namespace Tests\Ledger;

use App\Domain\Ledger\Models\CompanyProfile;
use App\Domain\Ledger\OpeningBalanceService;
use App\Domain\Reports\Export\ReportRenderer;
use App\Domain\Reports\Export\ReportSheetFactory;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;
use OpenSpout\Reader\CSV\Reader as CsvReader;
use OpenSpout\Reader\XLSX\Reader as XlsxReader;

/**
 * Export (docs/specs/03 §2). Every generated book, statement and report must
 * carry the header/footer block of RMC 5-2021 Annex B item 4 — registered
 * name, address, TIN with branch, software name AND version, the generating
 * user and the timestamp. A book without it is not a compliant book, so
 * these tests check the block in every format.
 */
class ReportExportTest extends LedgerTestCase
{
    /** @var list<string> */
    private array $files = [];

    protected function setUp(): void
    {
        parent::setUp();

        CompanyProfile::query()->where('id', 1)->update([
            'registered_name' => 'Soro Test Trading Inc.',
            'registered_address' => '123 Ayala Avenue, Makati City, 1226',
            'tin' => '246813579',
            'accn' => 'AC-2026-000123',
        ]);

        app(OpeningBalanceService::class)->post(
            ['1000' => 500_000, '3000' => 500_000],
            CarbonImmutable::now()->startOfYear()
        );

        $this->posting()->post($this->draft([
            ['1100', 300_000, 0],
            ['4000', 0, 300_000],
        ], ['journalBook' => 'sales']));
    }

    protected function tearDown(): void
    {
        foreach ($this->files as $file) {
            @unlink($file);
        }

        parent::tearDown();
    }

    private function tempPath(): string
    {
        $path = tempnam(sys_get_temp_dir(), 'soro-export-');
        $this->files[] = $path;

        return $path;
    }

    private function currentPeriodId(): int
    {
        return (int) DB::table('fiscal_periods')
            ->whereDate('start_date', '<=', CarbonImmutable::now()->toDateString())
            ->whereDate('end_date', '>=', CarbonImmutable::now()->toDateString())
            ->where('period_no', '<=', 12)
            ->value('id');
    }

    /** @return list<list<string>> */
    private function readXlsx(string $path): array
    {
        $reader = new XlsxReader;
        $reader->open($path);
        $rows = [];

        foreach ($reader->getSheetIterator() as $sheet) {
            foreach ($sheet->getRowIterator() as $row) {
                $rows[] = array_map(
                    fn ($cell) => $cell->getValue() === null ? '' : (string) $cell->getValue(),
                    $row->cells
                );
            }
            break;
        }

        $reader->close();

        return $rows;
    }

    public function test_the_xlsx_trial_balance_carries_the_mandatory_header_and_ties(): void
    {
        $sheet = app(ReportSheetFactory::class)->trialBalance($this->currentPeriodId());
        $path = app(ReportRenderer::class)->xlsx($sheet, $this->tempPath());

        $rows = $this->readXlsx($path);
        $flat = implode("\n", array_map(fn (array $row) => implode('|', $row), $rows));

        // RMC 5-2021 Annex B item 4, every element of it.
        $this->assertStringContainsString('Soro Test Trading Inc.', $flat);
        $this->assertStringContainsString('123 Ayala Avenue', $flat);
        $this->assertStringContainsString('VAT REG. TIN 246-813-579-00000', $flat);
        $this->assertStringContainsString(config('compliance.software_name'), $flat);
        $this->assertStringContainsString(config('compliance.software_version'), $flat);
        $this->assertStringContainsString('ACCN AC-2026-000123', $flat);
        $this->assertStringContainsString('generated by', $flat);

        // The totals row is the trial balance's own tie-out.
        $total = collect($rows)->first(fn (array $row) => ($row[1] ?? '') === 'TOTAL');
        $this->assertNotNull($total);
        $this->assertSame($total[2], $total[3], 'Debits must equal credits in the export too.');
    }

    /** Money must be a NUMBER in a spreadsheet, or the reader cannot sum it. */
    public function test_money_cells_are_numeric_in_xlsx_and_expressed_in_pesos(): void
    {
        $sheet = app(ReportSheetFactory::class)->trialBalance($this->currentPeriodId());
        $path = app(ReportRenderer::class)->xlsx($sheet, $this->tempPath());

        $reader = new XlsxReader;
        $reader->open($path);
        $numericSeen = false;

        foreach ($reader->getSheetIterator() as $sheetIterator) {
            foreach ($sheetIterator->getRowIterator() as $row) {
                $cells = $row->cells;

                if (($cells[0]->getValue() ?? '') !== '1100') {
                    continue;
                }

                // 300,000 centavos of A/R exports as 3000.00 pesos.
                $this->assertIsNumeric($cells[2]->getValue());
                $this->assertEqualsWithDelta(3000.0, (float) $cells[2]->getValue(), 0.001);
                $numericSeen = true;
            }
            break;
        }

        $reader->close();
        $this->assertTrue($numericSeen, 'The A/R row must appear in the export.');
    }

    public function test_the_csv_export_carries_the_header_and_the_rows(): void
    {
        $sheet = app(ReportSheetFactory::class)->journal(
            CarbonImmutable::now()->startOfYear()->toDateString(),
            CarbonImmutable::now()->endOfYear()->toDateString(),
        );

        $path = app(ReportRenderer::class)->csv($sheet, $this->tempPath());
        $contents = (string) file_get_contents($path);

        $this->assertStringContainsString('Soro Test Trading Inc.', $contents);
        $this->assertStringContainsString('VAT REG. TIN 246-813-579-00000', $contents);
        $this->assertStringContainsString('Account code', $contents);
        $this->assertStringContainsString('1100', $contents);

        // One row per LINE, which is the columnar shape the BIR books use.
        $reader = new CsvReader;
        $reader->open($path);
        $dataRows = 0;
        foreach ($reader->getSheetIterator() as $csvSheet) {
            foreach ($csvSheet->getRowIterator() as $row) {
                $cells = $row->toArray();
                if (($cells[4] ?? '') !== '' && preg_match('/^\d{4}$/', (string) $cells[4])) {
                    $dataRows++;
                }
            }
        }
        $reader->close();

        // Opening balance (2 lines) + the sale (2 lines).
        $this->assertSame(4, $dataRows);
    }

    public function test_every_report_renders_to_html_with_its_header(): void
    {
        $factory = app(ReportSheetFactory::class);
        $renderer = app(ReportRenderer::class);
        $periodId = $this->currentPeriodId();
        $year = CarbonImmutable::now();

        $sheets = [
            'Trial Balance' => $factory->trialBalance($periodId),
            'Balance Sheet' => $factory->balanceSheet($periodId),
            'Income Statement' => $factory->incomeStatement($periodId),
            'General Ledger' => $factory->generalLedger(
                $this->accountId('1000'),
                $year->startOfYear()->toDateString(),
                $year->endOfYear()->toDateString(),
            ),
            'Sales Journal' => $factory->journal(
                $year->startOfYear()->toDateString(),
                $year->endOfYear()->toDateString(),
                'sales',
            ),
        ];

        foreach ($sheets as $title => $sheet) {
            $html = $renderer->html($sheet);

            $this->assertStringContainsString($title, $html, "{$title} must print its own title.");
            $this->assertStringContainsString('Soro Test Trading Inc.', $html);
            $this->assertStringContainsString('VAT REG. TIN 246-813-579-00000', $html);
            $this->assertStringContainsString(config('compliance.software_version'), $html);
        }
    }

    /** The balance sheet export shows the equity that makes it balance. */
    public function test_the_balance_sheet_export_shows_net_income_inside_equity(): void
    {
        $this->posting()->post($this->draft([
            ['5000', 120_000, 0],
            ['1000', 0, 120_000],
        ]));

        $sheet = app(ReportSheetFactory::class)->balanceSheet($this->currentPeriodId());
        $html = app(ReportRenderer::class)->html($sheet);

        $this->assertStringContainsString('Net income for the period', $html);

        $assets = collect($sheet->totals)->firstWhere('name', 'TOTAL ASSETS');
        $claims = collect($sheet->totals)->firstWhere('name', 'TOTAL LIABILITIES AND EQUITY');
        $this->assertSame($assets['amount'], $claims['amount']);
    }

    public function test_reports_render_to_an_actual_pdf(): void
    {
        if (! is_dir(base_path('node_modules/puppeteer'))) {
            $this->markTestSkipped('Requires puppeteer/Chrome — run `npm install` to exercise the PDF path.');
        }

        $sheet = app(ReportSheetFactory::class)->trialBalance($this->currentPeriodId());
        $path = app(ReportRenderer::class)->pdf($sheet, $this->tempPath().'.pdf');
        $this->files[] = $path;

        $this->assertFileExists($path);
        $this->assertSame('%PDF', file_get_contents($path, false, null, 0, 4));
        $this->assertGreaterThan(1000, filesize($path));
    }

    public function test_an_unknown_export_format_is_refused(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessageMatches('/Unsupported report format/');

        app(ReportRenderer::class)->render(
            app(ReportSheetFactory::class)->trialBalance($this->currentPeriodId()),
            'docx',
            'trial-balance',
        );
    }
}
