<?php

namespace App\Domain\Reports\Export;

/**
 * One report, flattened into a tabular shape that every exporter can render
 * (docs/specs/03 §2 — "generate the books, exportable to `.csv`/`.dat` and
 * print-faithful PDF").
 *
 * The point of the intermediate shape is that a report is described ONCE and
 * comes out as XLSX, CSV and PDF from the same description, all carrying the
 * same mandatory header. A format-specific report would inevitably drift.
 */
class ReportSheet
{
    /**
     * @param  array<string, string|null>  $header  the mandatory BIR block
     * @param  list<ReportColumn>  $columns
     * @param  list<array<string, mixed>>  $rows
     * @param  list<array<string, mixed>>  $totals  footer rows, same keys as $rows
     */
    public function __construct(
        public readonly string $title,
        public readonly ?string $subtitle,
        public readonly array $header,
        public readonly array $columns,
        public readonly array $rows,
        public readonly array $totals = [],
    ) {}

    /** @return list<string> */
    public function labels(): array
    {
        return array_map(fn (ReportColumn $column) => $column->label, $this->columns);
    }

    /**
     * The header/footer lines RMC 5-2021 Annex B item 4 requires on every
     * generated output. Rendered above the table in every format.
     *
     * @return list<string>
     */
    public function headerLines(): array
    {
        return array_values(array_filter([
            $this->header['registered_name'] ?? null,
            $this->header['registered_address'] ?? null,
            $this->header['tin'] ?? null,
            $this->title.($this->subtitle === null ? '' : " — {$this->subtitle}"),
        ]));
    }

    /** @return list<string> */
    public function footerLines(): array
    {
        $software = $this->header['software'] ?? '';
        $accn = ($this->header['accn'] ?? null) === null ? '' : " · ACCN {$this->header['accn']}";
        $by = $this->header['generated_by'] ?? 'system';
        $at = $this->header['generated_at'] ?? '';

        return [trim("{$software}{$accn} · generated by {$by} on {$at}")];
    }
}
